<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <SignAssembly>False</SignAssembly>
    <PackageId>Zimmy.PowerShell.Testing.Framework</PackageId>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>PowerShell Testing Framework</Title>
    <Company />
    <Authors>Torsten Zimmermann</Authors>
    <Description>Components for testdriven development of PowerShell cmdlets</Description>
    <Copyright>Copyright © 2023</Copyright>
    <PackageTags>PowerShell, C#</PackageTags>
    <PackageOutputPath>$(OutputPath)\NuGet</PackageOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.PowerShell.SDK" Version="7.6.6" />
  </ItemGroup>

</Project>
